/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.puntoventa.vistas;

import com.puntoventa.conexion.TestConexion;
import com.puntoventa.style.lbl_boton;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author dbpan
 */
public class frm_menu extends javax.swing.JFrame {

    /**
     * Creates new form frm_menu
     */
    public frm_menu() {
        initComponents();
        applyButtonStyles();
        scaleLogoImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_bg = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        lbl_ventas = new javax.swing.JLabel();
        lbl_clientes = new javax.swing.JLabel();
        lbl_productos = new javax.swing.JLabel();
        lbl_vendedores = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 626));
        setSize(new java.awt.Dimension(1000, 625));

        jp_bg.setBackground(new java.awt.Color(0, 102, 204));
        jp_bg.setMinimumSize(new java.awt.Dimension(1000, 625));
        jp_bg.setPreferredSize(new java.awt.Dimension(1000, 625));
        jp_bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(54, 70, 78));

        lbl_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/puntoventa/recursos/venta.png"))); // NOI18N
        lbl_ventas.setText("Ventas");
        lbl_ventas.setToolTipText("");
        lbl_ventas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ventasMouseClicked(evt);
            }
        });

        lbl_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/puntoventa/recursos/personas.png"))); // NOI18N
        lbl_clientes.setText("Clientes");
        lbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_clientesMouseClicked(evt);
            }
        });

        lbl_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/puntoventa/recursos/agregar-producto.png"))); // NOI18N
        lbl_productos.setText("Productos");
        lbl_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_productosMouseClicked(evt);
            }
        });

        lbl_vendedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/puntoventa/recursos/vendedor.png"))); // NOI18N
        lbl_vendedores.setText("Vendedores");
        lbl_vendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_vendedoresMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_ventas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_vendedores, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lbl_ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lbl_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(lbl_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(lbl_vendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 188, Short.MAX_VALUE))
        );

        jp_bg.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 210, 552));

        body.setLayout(new java.awt.BorderLayout());
        jp_bg.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 73, 790, 552));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/puntoventa/recursos/pngwing.com.png"))); // NOI18N
        lbl_logo.setText("jLabel2");
        lbl_logo.setPreferredSize(new java.awt.Dimension(41, 50));
        jp_bg.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 80, 70));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Punto de venta");
        jp_bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 490, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_ventasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ventasMouseClicked

    }//GEN-LAST:event_lbl_ventasMouseClicked
    private void scaleLogoImage() {
        try {
            // Cargar la imagen desde los recursos
            InputStream imgStream = getClass().getResourceAsStream("/com/puntoventa/recursos/pngwing.com.png");
            if (imgStream == null) {
                throw new IOException("Imagen no encontrada");
            }
            BufferedImage img = ImageIO.read(imgStream);

            // Escalar la imagen al tamaño del JLabel
            Image scaledImage = img.getScaledInstance(lbl_logo.getWidth(), lbl_logo.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(scaledImage);

            // Establecer la imagen escalada como icono del JLabel
            lbl_logo.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void lbl_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_clientesMouseClicked
        showForm(new pnf_clientes());
    }//GEN-LAST:event_lbl_clientesMouseClicked

    private void lbl_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_productosMouseClicked
        TestConexion obj = new TestConexion();
        obj.main(new String[]{});
    }//GEN-LAST:event_lbl_productosMouseClicked

    private void lbl_vendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_vendedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_vendedoresMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_menu().setVisible(true);
            }
        });
    }

    public void showForm(Component com) {
        body.removeAll();
        body.add(com);
        body.repaint();
        body.revalidate();
    }

    private void applyButtonStyles() {
        lbl_boton.applyButtonStyle(lbl_ventas);
        lbl_boton.applyButtonStyle(lbl_clientes);
        lbl_boton.applyButtonStyle(lbl_productos);
        lbl_boton.applyButtonStyle(lbl_vendedores);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel body;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jp_bg;
    private javax.swing.JLabel lbl_clientes;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_productos;
    private javax.swing.JLabel lbl_vendedores;
    private javax.swing.JLabel lbl_ventas;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
