/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.puntoventa.vistas;

import com.puntoventa.controladores.clientes;
import com.puntoventa.style.txt_estilos;

/**
 *
 * @author dbpan
 */
public class pnf_clientes extends javax.swing.JPanel {

    /**
     * Creates new form pnl_clientes
     */
    public pnf_clientes() {
        initComponents();
        applyTextfieldStyles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        btn_Borrar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Cedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(790, 552));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 153, -1));
        add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 155, -1));
        add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 77, -1));
        add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 284, -1));

        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 155, -1));

        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel2.setText("Apellido");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel3.setText("Edad");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        jLabel4.setText("Correo:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jLabel5.setText("Telefono");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });
        add(btn_Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 129, 76));

        btn_Borrar.setText("Borrar");
        add(btn_Borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 126, 76));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.setToolTipText("");
        add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 130, 76));

        jLabel6.setText("Cedula");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        add(txt_Cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 155, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setText("Numero:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel8.setText("00");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 20));
    }// </editor-fold>//GEN-END:initComponents
private void applyTextfieldStyles() {
        txt_estilos.applyTextFieldStyle(txt_nombre);
        txt_estilos.applyTextFieldStyle(txt_apellido);
        txt_estilos.applyTextFieldStyle(txt_Cedula);
        txt_estilos.applyTextFieldStyle(txt_edad);
        txt_estilos.applyTextFieldStyle(txt_correo);
        txt_estilos.applyTextFieldStyle(txt_telefono);

    }
    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        clientes obj_C = new clientes();
        obj_C.setNombre(txt_nombre.getText().trim());
        obj_C.setApellido(txt_apellido.getText().trim());
        obj_C.setEdad(Integer.parseInt(txt_edad.getText().trim()));
        obj_C.setCorreo(txt_correo.getText().trim());
        obj_C.setTelefono(txt_telefono.getText().trim());

        obj_C.mostrar();


    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Borrar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_Cedula;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
